CREATE TABLE Users (
	UserID INT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	FullName NVARCHAR(101) NOT NULL,
	ShortName NVARCHAR(52) NOT NULL,
	Login VARCHAR(8) NOT NULL,
	Password NVARCHAR(30) NOT NULL,
	ConfirmPassword NVARCHAR(30) NOT NULL
)

CREATE TABLE Addresses (
	AddressID INT IDENTITY(1,1) PRIMARY KEY,
	Country NVARCHAR(200) NOT NULL,
	Region NVARCHAR(200) NOT NULL,
	City NVARCHAR(200) NOT NULL,
	Street NVARCHAR(200) NOT NULL,
	House NVARCHAR(10) NOT NULL,
	Apartment SMALLINT NULL
)

CREATE TABLE Clients (
	ClientID INT IDENTITY(1,1) PRIMARY KEY,
	UserID INT UNIQUE,
	AddressID INT NOT NULL,
	Age TINYINT NOT NULL,
	PhoneNumber INT NOT NULL,
	CONSTRAINT FK_Clients_Users FOREIGN KEY (UserID) REFERENCES Users (UserID),
	CONSTRAINT FK_Clients_Addresses FOREIGN KEY (AddressID) REFERENCES Addresses (AddressID)
)
