CREATE TABLE Users (
	UserID INT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	FullName AS (FirstName + LastName) PERSISTED,
	Login NVARCHAR(8) NOT NULL UNIQUE,
	Password NVARCHAR(30) NOT NULL
)

CREATE TABLE Clients (
	ClientID INT IDENTITY(1,1) PRIMARY KEY,
	UserID INT NOT NULL UNIQUE,
	Age TINYINT NOT NULL,
	PhoneNumber BIGINT NOT NULL
)

CREATE TABLE Accounts (
	AccountID INT IDENTITY(1,1) PRIMARY KEY,
	AccountNumber BIGINT NOT NULL UNIQUE,
	AccountType TINYINT NOT NULL,
	Balance DECIMAL(18,2) NOT NULL,
	Currency TINYINT NOT NULL,
	TransactionsLimitPerDay TINYINT NOT NULL,
	IsAccountBlocked BIT NOT NULL DEFAULT 1,
	ClientID INT NOT NULL,
	CONSTRAINT FK_Accounts_Clients
		FOREIGN KEY (ClientID) 
		REFERENCES Clients(ClientID)
)

CREATE TABLE Deposits (
	DepositID INT IDENTITY(1,1) PRIMARY KEY,
	DepositType NVARCHAR(200) NOT NULL,
	Amount DECIMAL(18,2) NOT NULL,
	InterestRate DECIMAL NOT NULL,
	DepositTermMonths TINYINT NOT NULL,
	ClientID INT NOT NULL,
	CONSTRAINT FK_Deposits_Clients
		FOREIGN KEY (ClientID) 
		REFERENCES Clients(ClientID)
)

CREATE TABLE Loans (
	LoanID INT IDENTITY(1,1) PRIMARY KEY,
	LoanType NVARCHAR(200) NOT NULL,
	Amount DECIMAL(18,2) NOT NULL,
	InterestRate DECIMAL NOT NULL,
	LoanTermMonths TINYINT NOT NULL,
	ClientID INT NOT NULL,
	CONSTRAINT FK_Loans_Clients
		FOREIGN KEY (ClientID) 
		REFERENCES Clients(ClientID)
)

CREATE TABLE Transactions (
	TransactionID INT IDENTITY(1,1) PRIMARY KEY,
	TransactionDate DATETIME NOT NULL,
	Amount DECIMAL(18,2) NOT NULL,
	TransactionType TINYINT NOT NULL,
	SenderAccount BIGINT NOT NULL,
	ReceiverAccount BIGINT NOT NULL,
	AccountID INT NOT NULL,
	CONSTRAINT FK_Transactions_Accounts
		FOREIGN KEY (AccountID) 
		REFERENCES Accounts(AccountID)
)
